apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: org1-peer2
  namespace: monitoring
spec:
  namespaceSelector:
    # todo: use ${NS} and establish RBAC for visibility from system:serviceaccount:monitoring:prometheus-k8s
    matchNames:
      - default
  selector:
    matchLabels:
      app: org1-peer2
  endpoints:
    - port: operations
      scheme: https
      # todo: add kustomization target to create org1 monitoring secret from
      # cacert.pem = temp/enrollments/org1/users/org1admin/tls/cacerts/default-org1-ca-ca-localho-st-443-tlsca.pem
      # cert.pem = temp/enrollments/org1/users/org1admin/tls/signcerts/cert.pem
      # key.pem = temp/enrollments/org1/users/org1admin/tls/keystore/key.pem
      tlsConfig:
        serverName: org1-peer2
        ca:
          secret:
            name: org1-servicemonitor-tls-secret
            key: cacert.pem
        cert:
          secret:
            name: org1-servicemonitor-tls-secret
            key: cert.pem
        keySecret:
          name: org1-servicemonitor-tls-secret
          key: key.pem
