apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    categories: Database
    certified: "true"
    containerImage: todo:update
    createdAt: "2020-07-14T00:00:00Z"
    description: TODO
    operators.operatorframework.io/builder: operator-sdk-v1.24.1
    operators.operatorframework.io/internal-objects: '["ibpcas.ibp.com","ibppeers.ibp.com","ibporderers.ibp.com"]'
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: ""
  name: fabric-opensource-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: TODO
  displayName: Fabric Opensource Operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgdmlld0JveD0iMCAwIDMyIDMyIj48cGF0aCBkPSJNMTYsMEExNiwxNiwwLDEsMCwzMiwxNiwxNiwxNiwwLDAsMCwxNiwwWk05LDIySDdWMTBIOVptMTMsM0gxMFYyM0gyMlpNMjIsOUgxMFY3SDIyWm0zLDEzSDIzVjEwaDJaIiBzdHlsZT0iZmlsbDojMTMxNzFhIi8+PC9zdmc+Cg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - hyperledger
  - fabric
  maturity: alpha
  provider:
    name: Opensource
  version: 1.0.0
